### ISSUE TITLE
Motor turnOn and turnOff do not work when using speed or pwm.

### ISSUE THREAD

**Issue by tejas4patel** [hybridgroup/cylon-raspi#27]
There's a bug when usin turn on or turn off with motor GPIO driver on raspi.

```
pi@raspberrypi ~ $ node l298n-h-bridge.js 
I, [2014-12-07T19:23:33.910Z]  INFO -- : Initializing connections.
I, [2014-12-07T19:23:36.786Z]  INFO -- : Initializing devices.
I, [2014-12-07T19:23:36.862Z]  INFO -- : Starting connections.
I, [2014-12-07T19:23:36.887Z]  INFO -- : Starting devices.
I, [2014-12-07T19:23:36.896Z]  INFO -- : Working.

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at DigitalPin.EventEmitter.emit (events.js:74:15)
    at DigitalPin._setModeCallback (/home/pi/node_modules/cylon-raspi/node_modules/cylon/lib/io/digital-pin.js:147:17)
    at DigitalPin.<anonymous> (/home/pi/node_modules/cylon-raspi/node_modules/cylon/lib/io/digital-pin.js:141:10)
    at fs.js:944:21
    at Object.oncomplete (fs.js:107:15)

```

**Comment by edgarsilva** [comment]
Forgot to close this issue before, closing now.
